vp0:
 extends:
  file: compose-defaults.yml
  service: vp
 ports:
  - "7050:7050"
  - "7051:7051"
  - "7052:7052"
 environment:
  - CORE_PEER_ID=vp0
  - CORE_PEER_DISCOVERY_PERIOD=1s
  - CORE_PEER_DISCOVERY_TOUCHPERIOD=1s

vp1:
 extends:
  file: compose-defaults.yml
  service: vp
 ports:
  - "8050:7050"
  - "8051:7051"
  - "8052:7052"
 environment:
  - CORE_PEER_ID=vp1
  - CORE_PEER_ADDRESS=vp0:7051
  - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
 links:
    - vp0
    - vp2
    - vp3
    - vp4

vp2:
  extends:
    file: compose-defaults.yml
    service: vp
  ports:
    - "9050:7050"
    - "9051:7051"
    - "9052:7052"
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_ADDRESS=vp0:7051
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  links:
    - vp0
    - vp3
    - vp4

vp3:
  extends:
    file: compose-defaults.yml
    service: vp
  ports:
    - "10050:7050"
    - "10051:7051"
    - "10052:7052"
  environment:
    - CORE_PEER_ID=vp3
    - CORE_PEER_ADDRESS=vp0:7051
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  links:
    - vp0
    - vp4

vp4:
  extends:
    file: compose-defaults.yml
    service: vp
  ports:
    - "11050:7050"
    - "11051:7051"
    - "11052:7052"
  environment:
    - CORE_PEER_ID=vp4
    - CORE_PEER_ADDRESS=vp0:7051
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  links:
    - vp0