vp0:
 extends:
  file: compose-defaults.yml
  service: vp
 ports:
  - "7050:7050"
  - "7051:7051"
  - "7052:7052"
 environment:
  - CORE_PEER_ID=vp0
  - CORE_PEER_DISCOVERY_PERIOD=1s
  - CORE_PEER_DISCOVERY_TOUCHPERIOD=1s