version: '2'
services:
  baseimage:
    image: hyperledger/fabric-baseimage:x86_64-0.2.0

  vp0:
    image: hyperledger/fabric-peer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/vladyslav/Documents/Study/Trento/ResearchProj/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    command: sh -c "sleep 10; peer node start"
    
  vp1:
    image: hyperledger/fabric-peer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/vladyslav/Documents/Study/Trento/ResearchProj/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets
    ports:
      - "8050:7050"
      - "8051:7051"
      - "8053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    command: sh -c "sleep 10; peer node start"
    links:
      - vp0

  vp2:
    image: hyperledger/fabric-peer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/vladyslav/Documents/Study/Trento/ResearchProj/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets
    ports:
      - "9050:7050"
      - "9051:7051"
      - "9053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    command: sh -c "sleep 10; peer node start"
    links:
      - vp0

  vp3:
    image: hyperledger/fabric-peer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/vladyslav/Documents/Study/Trento/ResearchProj/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/java/FutureMarkets
    ports:
      - "10050:7050"
      - "10051:7051"
      - "10053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    command: sh -c "sleep 10; peer node start"
    links:
      - vp0
